# Generated by Django 5.0.4 on 2024-06-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maincategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=20)),
                ('sdesc', models.TextField()),
                ('simages', models.ImageField(upload_to='images/subcategory')),
                ('maincategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.maincategory')),
            ],
        ),
    ]
