# Generated by Django 5.0.4 on 2024-06-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
