# Generated by Django 5.0.4 on 2024-06-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_alter_product_available_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trending',
            field=models.BooleanField(default=True),
        ),
    ]
